kind: Deployment
apiVersion: apps/v1
metadata:
  name: codingtch-processing-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
        app: codingtch-processing-deployment
  template:
    metadata:
      labels:
        app: codingtch-processing-deployment
    spec:
      containers:
        - name: codingtch-processing-deployment
          image: popirtanvlad/codingtch-processing
          imagePullPolicy: Always
          ports:
            - containerPort: 24001
      restartPolicy: Always
