apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVZUTkdCQUpSMzc3RFozT1g=
  AWS_SECRET_ACCESS_KEY: R3ZjMWlUejFRbHdKUldKWjhyTnRhU1MzUzJFUFE5U0Z1eUx4aU5KTg==